WITH MAX_FISH AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LEN
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT ID, FISH_NAME, LENGTH
FROM
(SELECT ID, A.FISH_TYPE AS FISH_TYPE, FISH_NAME, LENGTH
 FROM FISH_INFO A JOIN FISH_NAME_INFO B ON A.FISH_TYPE=B.FISH_TYPE) T
 JOIN MAX_FISH C
 ON T.FISH_TYPE=C.FISH_TYPE AND T.LENGTH=C.MAX_LEN